### ISSUE TITLE
Default value in username field

### ISSUE THREAD

**Issue by pravj** [black-perl/Tweety#1]
Hey @black-perl,

This is regarding a comment on reddit-ml thread, where I found this repository. I too felt this need though.

You should better leave the username we use, in the username field.
I mean it's not fine to fill the same thing again and again, unless we are trying a different user.

**Comment by darxtrix** [comment]
Hey,

But there are **no** restrictions on the number of user names you can use. As, it uses the public tweets corresponding to a twitter handle. A user may have entered many twitter handles.

Best would be to ask the user, which he/she wants to use as default and fill this default one next time.

Regards.

**Comment by pravj** [comment]
Hi,

Yeah, I know that there aren't any restrictions on the user handles you use.

But I don't think as a user I would like entering **my** handle again, if I want to see one more generated tweet for my profile, then one more and so on.

It's natural for me to enter it, if I'm trying for any other person's profile.
Sorry if I was not clear from the issue title earlier.

**Comment by darxtrix** [comment]
Yeah, pretty true. Actually, I didn't implemented that because I don't want to involve any database stuff. Tweety does not use any database in the backend for now. 
Maybe, this can be achieved by setting a cookie. Have you any thoughts on it ?

**Comment by darxtrix** [comment]
Okay, you mean left the name as it is for the next tweet ? I was thinking hell wrong. Oops sorry.
Just pushed it, checkout !

**Comment by pravj** [comment]
Yeah, Cool. That's exactly what I meant. :+1:

I should close this now, I think.

**Comment by darxtrix** [comment]
yeah, thanks for this :+1:
